apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: flux-system
spec:
  interval: 50m
  chart:
    spec:
      chart: sealed-secrets
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
      interval: 65m

