# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: cert-manager-controller
#   namespace: flux-system
# spec:
#   interval: 5m
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#   serviceAccountName: kustomize-controller
#   path: ./infrastructure/controllers/cert-manager
#   prune: true
#   patches:
#     - patch: |
#         - op: add
#           path: /spec/values/serviceAccount/annotations	
#           value:
#             iam.gke.io/gcp-service-account: dns01-solver@k8s-dev-bd63.iam.gserviceaccount.com
#       target:
#         kind: HelmRelease
#         name: cert-manager
#         namespace: cert-manager
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: cert-manager-global-resources
#   namespace: flux-system
# spec:
#   interval: 5m
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#   serviceAccountName: kustomize-controller
#   path: ./infrastructure/configs/cert-manager
#   prune: true
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: flagger-controller
#   namespace: flux-system
# spec:
#   interval: 5m
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#   serviceAccountName: kustomize-controller
#   path: ./infrastructure/controllers/flagger
#   prune: true
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: flagger-configs
#   namespace: flux-system
# spec:
#   interval: 5m
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#   serviceAccountName: kustomize-controller
#   path: ./infrastructure/configs/flagger
#   prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: weave-gitops-controller
  namespace: flux-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  serviceAccountName: kustomize-controller
  path: ./infrastructure/controllers/weave-gitops
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: weave-policies
  namespace: flux-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  serviceAccountName: kustomize-controller
  path: ./infrastructure/configs/weave-policies
  prune: true

