apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongodb-cluster
  namespace: default
spec:
  members: 3
  arbiters: 1
  type: ReplicaSet
  version: "4.4.13"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: banker
      db: admin
      passwordSecretRef:
        name: base-secret
        key: password
      roles:
        - name: readWrite
          db: bankdb
      scramCredentialsSecretName: banker
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
