apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongodb-cluster
  namespace: default
spec:
  members: 3
  type: ReplicaSet
  version: "4.4.13"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: admin
      db: admin
      passwordSecretRef:
        name: base-secret
        key: password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
      scramCredentialsSecretName: mongo-admin-credentials
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
