apiVersion: apps/v1
kind: Deployment
metadata:
  name: store
  labels:
    app: store
spec:
  selector:
    matchLabels:
      app: store
  template:
    metadata:
      labels:
        app: store
    spec:
      containers:
      - name: store
        image: ghcr.io/kol-ratner/dream/store:main
        imagePullPolicy: Always
        env:
          - name: RABBITMQ_HOST
            value: rabbitmq.data.svc.cluster.local
        ports:
          - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"