apiVersion: clustersecret.io/v1
kind: ClusterSecret
metadata:
  name: mongodb-cluster-banker-credentials
  namespace: clustersecret
matchNamespace:
  - default
data:
  valueFrom:
    secretKeyRef:
      name: mongodb-cluster-admin-banker
      namespace: mongodb