apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank
  namespace: default
  labels:
    app: bank
spec:
  selector:
    matchLabels:
      app: bank
  template:
    metadata:
      labels:
        app: bank
    spec:
      containers:
      - name: bank
        image: ghcr.io/kol-ratner/dream/bank:main
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 15
        env:
          - name: SERVICE_PORT
            value: 8080
          - name: RABBITMQ_HOST
            valueFrom:
              secretKeyRef:
                name: rabbitmq-cluster-default-user
                key: host
          - name: RABBITMQ_USER
            valueFrom:
              secretKeyRef:
                name: rabbitmq-cluster-default-user
                key: username
          - name: RABBITMQ_PASSWORD
            valueFrom:
              secretKeyRef:
                name: rabbitmq-cluster-default-user
                key: password
          - name: MONGODB_HOST
            value: mongodb-cluster-svc.mongodb.svc.cluster.local
          - name: MONGODB_REPLICASET
            value: mongodb-cluster
          - name: MONGODB_USER
            value: banker
          - name: MONGODB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodb-cluster-banker-credentials
                key: password
        ports:
          - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"