apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: store
spec:
  project: default
  source:
    path: store/kubernetes
    repoURL: 'https://github.com/kol-ratner/dream'
    targetRevision: HEAD
  destination:
    namespace: store
    server: 'https://kubernetes.default.svc'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: store
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/kol-ratner/dream.git'
    path: store/k8s.yaml
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true