apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: flux-system
spec:
  interval: 50m
  chart:
    spec:
      chart: postgresql
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: bitnami
      interval: 65m
  # https://github.com/bitnami/charts/blob/main/bitnami/postgresql/values.yaml
  values: {}