apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rabbitmq
  namespace: flux-system
spec:
  interval: 50m
  chart:
    spec:
      chart: rabbitmq
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: bitnami
      interval: 65m
  # https://github.com/bitnami/charts/blob/main/bitnami/rabbitmq/values.yaml
  values:
    namespaceOverride: default