apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rabbitmq-cluster-operator
  namespace: flux-system
spec:
  interval: 50m
  chart:
    spec:
      chart: rabbitmq-cluster-operator
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 65m
  targetNamespace: rabbitmq-system
  install:
    createNamespace: true
  # https://github.com/bitnami/charts/blob/main/bitnami/rabbitmq/values.yaml
  values: {}
---
# apiVersion: helm.toolkit.fluxcd.io/v2beta1
# kind: HelmRelease
# metadata:
#   name: postgresql-ha
#   namespace: flux-system
# spec:
#   interval: 50m
#   chart:
#     spec:
#       chart: postgresql-ha
#       version: "*"
#       sourceRef:
#         kind: HelmRepository
#         name: bitnami
#         namespace: flux-system
#       interval: 65m
#   targetNamespace: default
#   install:
#     createNamespace: false
#   # https://github.com/bitnami/charts/blob/main/bitnami/postgresql/values.yaml
#   values: {}