apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mongodb-operator
  namespace: flux-system
spec:
  interval: 50m
  chart:
    spec:
      chart: community-operator
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: mongodb
        namespace: flux-system
      interval: 65m
  targetNamespace: mongodb
  install:
    createNamespace: true
  # https://github.com/bitnami/charts/blob/main/bitnami/rabbitmq/values.yaml
  values: {}
