name: Pe-Merge Checks
on:
  workflow_dispatch: {}
  pull_request:
    branches: 
      - "main"
    paths:
      - "bank"
      - "store"
permissions:
  id-token: write
  contents: read
  pull-requests: read
jobs:
  pre_merge:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: ["store", "bank"]
    defaults:
      run:
        working-directory: ${{ matrix.app }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install PDM
        run: |
          python -m pip install --upgrade pip
          pip install pdm

      - name: Install dependencies
        run: pdm install --dev
      
      - name: Python Linting
        run: pdm run flake8 src tests
      
      - name: Install Flake8
        run: |
          pdm run pytest tests
